(ns autoclave.markdown-test
  (:require [autoclave.core :refer :all]
            [clojure.string :refer [capitalize]]
            [clojure.test :refer [deftest is]]))

(def example
  (str "# Header 1\n"
       "## Header 2\n"
       "Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n"
       "<span style=\"color: red\">Some HTML.</span>\n"
       "http://google.com.\n"
       "And here is a [[wiki]] link."))

(deftest test-none
  (is (= (markdown-to-html example)
         (str "<h1>Header 1</h1>\n"
              "<h2>Header 2</h2>\n"
              "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
              "<span style=\"color: red\">Some HTML.</span> "
              "http://google.com. "
              "And here is a [[wiki]] link.</p>"))))

(deftest test-supress-all-html
  (let [processor (markdown-processor :suppress-all-html)]
    (is (= (markdown-to-html processor example)
           (str "<h1>Header 1</h1>\n"
                "<h2>Header 2</h2>\n"
                "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
                "Some HTML. "
                "http://google.com. "
                "And here is a [[wiki]] link.</p>")))))

(deftest test-links
  (let [processor (markdown-processor :auto-links :wiki-links)]
    (is (= (markdown-to-html processor example)
           (str "<h1>Header 1</h1>\n"
                "<h2>Header 2</h2>\n"
                "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
                "<span style=\"color: red\">Some HTML.</span> "
                "<a href=\"http://google.com\">http://google.com</a>. "
                "And here is a <a href=\"./wiki.html\">wiki</a> link.</p>")))))

(deftest test-link-renderer
  (let [link-renderer (markdown-link-renderer
                       {:auto-link (fn [node]
                                     {:text (->> (.getText node)
                                                 (re-find #"://\.?(\w+).")
                                                 second
                                                 capitalize)
                                      :href (.getText node)
                                      :attributes ["class" "autolink"]})})
        processor (markdown-processor :auto-links)]
    (is (= (markdown-to-html processor link-renderer example)
           (str "<h1>Header 1</h1>\n"
                "<h2>Header 2</h2>\n"
                "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
                "<span style=\"color: red\">Some HTML.</span> "
                "<a href=\"http://google.com\" class=\"autolink\">Google</a>. "
                "And here is a [[wiki]] link.</p>")))))

(deftest test-all-md
  ;; all.tmp.md is the concatenated markdown file generated by
  ;; https://github.com/karlcow/markdown-testsuite ./cat-all.py
  (let [processor (markdown-processor :all)
        markdown (slurp (clojure.java.io/resource "all.tmp.md"))
        html (markdown-to-html processor markdown)]
    ;(println html)
    ;(spit "/tmp/all.tmp.html" html)
    ))
